openapi: 3.0.3
info:
  title: Customer API
  version: 1.0.0

servers:
  - url: http://localhost:8081

paths:
  /api/v1/customers:
    post:
      summary: Create customer
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        '201':
          description: Customer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'

    get:
      summary: Get all customers
      operationId: getAllCustomers
      responses:
        '200':
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerResponse'

  /api/v1/customers/{id}:
    get:
      summary: Get customer by id
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'

components:
  schemas:
    CreateCustomerRequest:
      type: object
      properties:
        name:
          type: string
        gender:
          type: string
        identification:
          type: string
        address:
          type: string
        phone:
          type: string
        password:
          type: string
        status:
          type: boolean

    CustomerResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        gender:
          type: string
        identification:
          type: string
        address:
          type: string
        phone:
          type: string
        status:
          type: boolean
