FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app
COPY ../banking-contracts banking-contracts
WORKDIR /app/banking-contracts
RUN mvn clean install -DskipTests
WORKDIR /app
COPY account-service account-service
WORKDIR /app/account-service
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/account-service/target/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]